---
- name: Include Source file variables
  include_vars: source-files-vars.yml

- name: Ensure line is in file
  lineinfile:
    path: "{{ recon_user_home_dir if user_created else ansible_env.HOME }}/{{ startup_file[ansible_distribution] }}"
    regexp: '^source'
    line: "source ~/.{{ item.value.path }}"
    state: present
    owner: '{{ recon_user_username if user_created else ansible_user_id }}'
    group: '{{ recon_user_username if user_created else ansible_user_id }}'
    mode: '0700'
  loop: "{{ recon_source_files|dict2items }}"

- name: Get Source files
  get_url:
    url: "{{ item.value.url }}"
    dest: "{{ recon_user_home_dir if user_created else ansible_env.HOME }}/{{ item.value.path }}"
    owner: "{{ recon_user_username if user_created else ansible_user_id }}"
    group: "{{ recon_user_username if user_created else ansible_user_id }}"
    mode: '0700'
  loop: "{{ recon_source_files|dict2items }}"
