---
- name: User Tasks | Include user variables
  include_vars: "User-vars.yml"

- name: User Tasks | Ensure privileged group exists
  group:
    name: "{{ group_membership }}"
    state: present

- name: User Tasks | Allow privileged group to have sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%{{ group_membership }}"
    line: "%{{ group_membership }} ALL=(ALL:ALL) ALL"
    validate: 'visudo -cf %s'

- name: User Tasks | Create user account
  user:
    name: "{{ username }}"
    state: present
    password: "{{ user_password | password_hash('sha512') }}"
    update_password: on_create
    append: true
    shell: "{{ preferred_shell }}"
    home: "{{ home_dir }}"
    groups: "{{ group_membership }}"
  register: user_created
  notify:
    - "User Tasks | Force password change"
